services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: smart_city_logistics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/smart_city_logistics
    depends_on:
      - db

volumes:
  db_data: